name: PR
on:
  pull_request:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    strategy:
      matrix:
        python-version: [3.9]
        step: ['test']
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools
      - name: Install EOS test framework
        run: |
          python3 -m pip install ipyeos
      - name: Run eosdebugger
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so eosdebugger &
      - name: test
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn build
          yarn test
  